# Generated by Django 4.0.6 on 2022-07-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mediums', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField(verbose_name='Date Completed')),
                ('img', models.CharField(max_length=250)),
            ],
        ),
    ]
